module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    colors: {
      transparent: "transparent",
      current: "currentColor",
      white: "#ffffff",
      red: "#ff441a",
      navy: "#2b3a63",
      sand: "#fcf5e6",
      gold: "#e5ae35",
    },
    extend: {
      fontFamily: {
        sans: ["dinosaur", "Arial", "sans-serif"],
        "sofia-pro": ["sofia-pro", "sans-serif"],
      },
      typography: ({ theme }) => ({
        navy: {
          css: {
            "--tw-prose-body": theme("colors.navy"),
            "--tw-prose-headings": theme("colors.navy"),
            "--tw-prose-lead": theme("colors.navy[700]"),
            "--tw-prose-links": theme("colors.navy[900]"),
            "--tw-prose-bold": theme("colors.navy[900]"),
            "--tw-prose-counters": theme("colors.navy[600]"),
            "--tw-prose-bullets": theme("colors.navy[400]"),
            "--tw-prose-hr": theme("colors.navy[300]"),
            "--tw-prose-quotes": theme("colors.navy[900]"),
            "--tw-prose-quote-borders": theme("colors.navy[300]"),
            "--tw-prose-captions": theme("colors.navy[700]"),
            "--tw-prose-code": theme("colors.navy[900]"),
            "--tw-prose-pre-code": theme("colors.navy[100]"),
            "--tw-prose-pre-bg": theme("colors.navy[900]"),
            "--tw-prose-th-borders": theme("colors.navy[300]"),
            "--tw-prose-td-borders": theme("colors.navy[200]"),
            "--tw-prose-invert-body": theme("colors.navy[200]"),
            "--tw-prose-invert-headings": theme("colors.white"),
            "--tw-prose-invert-lead": theme("colors.navy[300]"),
            "--tw-prose-invert-links": theme("colors.white"),
            "--tw-prose-invert-bold": theme("colors.white"),
            "--tw-prose-invert-counters": theme("colors.navy[400]"),
            "--tw-prose-invert-bullets": theme("colors.navy[600]"),
            "--tw-prose-invert-hr": theme("colors.navy[700]"),
            "--tw-prose-invert-quotes": theme("colors.navy[100]"),
            "--tw-prose-invert-quote-borders": theme("colors.navy[700]"),
            "--tw-prose-invert-captions": theme("colors.navy[400]"),
            "--tw-prose-invert-code": theme("colors.white"),
            "--tw-prose-invert-pre-code": theme("colors.navy[300]"),
            "--tw-prose-invert-pre-bg": "rgb(0 0 0 / 50%)",
            "--tw-prose-invert-th-borders": theme("colors.navy[600]"),
            "--tw-prose-invert-td-borders": theme("colors.navy[700]"),
          },
        },
      }),
    },
  },
  variants: {},
  plugins: [require("@tailwindcss/typography"), require("@tailwindcss/forms")],
}
